### ISSUE TITLE
Android images with Node.js v10.x?

### ISSUE THREAD

**Issue by mikemorris** [CircleCI-Public/example-images#1]
Was released in April and is the next LTS release, would be nice to have Android images with it for building React Native projects with a consistent Node.js version (the macos/xcode 9.4.1 and later releases are shipping with Node.js v10.x already).

**Comment by felicianotech** [comment]
Hi @mikemorris,

Aside from the Node.js image itself which has tags for various versions, the Node variants for our other images carry the LTS version of Node.js. So once 10.x becomes LTS, they will have it.

Also, please open Issues like this at the main repo for our images, https://github.com/circleci/circleci-images/issues. I know we have two repos which is slightly confusing, sorry about that.

**Comment by felicianotech** [comment]
Btw, if you still want to further discuss this, by all means reopen this Issue at the link I provided.
